name: "Arch package action(s)"
description: "GitHub Action to run Arch Linux's package tools"
author: 'valorekhov'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  operation:
    description: 'The operation to perform'
    required: true
    default: 'makefile-update'
  working-dir:
    description: 'The working directory to run the operation in'
    required: false
    default: ''
  rebuild-all:
    description: 'Rebuild all .SRCINFOs and/or packages without regard to modification status'
    required: false
    default: ''
  

runs:
  using: 'docker'
  image: 'Dockerfile'