name: Build `archlinux-{arm64v8,armv7hf}:base-devel` and `gha-makepkg:latest` multi-arch images
on: 
  workflow_dispatch:
    inputs:
      arch:
        description: 'Build only this arch'
        required: false
  push:
    paths:
    - ./.github/actions/makepkg/**
    branches:
    - main

jobs:
  build-basedevel-arm-images:
    runs-on: ubuntu-latest
    name: Build ARM archlinux-{arm64v8, armv7hf}:base-devel images
    if: github.event.inputs.arch == '' || github.event.inputs.arch == null || github.event.inputs.arch == matrix.platform
    strategy:
      matrix:
        platform:
        - arm64v8
        - armv7hf
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to GitHub docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Check if `archlinux-${{ matrix.platform }}:base-devel` image is available in the `ghcr` registry
      id: check_registry
      run: |
        docker pull ghcr.io/valorekhov/archlinux-${{ matrix.platform }}:base-devel || exit 0
        docker tag ghcr.io/valorekhov/archlinux-${{ matrix.platform }}:base-devel archlinux-${{ matrix.platform }}:base-devel
        echo "registry_has_base_devel_image=true" >> $GITHUB_OUTPUT

    - name: Build base-devel image from ArchLinux ARM tarball
      id: prepare_image
      if: steps.check_registry.outputs.registry_has_base_devel_image != 'true'
      run: |
        # Convert docker ARCH to archlinux-arm ARCH
        switch ('${{ matrix.platform }}') {
          'arm64v8' { $arch = 'aarch64' }
          'armv7hf' { $arch = 'armv7' }
        }
        wget "http://os.archlinuxarm.org/os/ArchLinuxARM-$arch-latest.tar.gz"
        gzip -d "ArchLinuxARM-$arch-latest.tar.gz"
        docker import "ArchLinuxARM-$arch-latest.tar" archlinux-${{ matrix.platform }}:latest
        docker image ls
        # docker build -t archlinux-${{ matrix.platform }}:base-devel -f ./tools/container-build/base-devel/Containerfile ./tools/container-build/base-devel

        switch ('${{ matrix.platform }}') {
          'arm64v8' { $platform = 'linux/amd64' }
          'armv7hf' { $platform = 'linux/arm/v7' }
        }
        echo "platform=$platform" >> $GITHUB_ENV
      
    - name: Build base-devel ArchLinux ARM image
      uses: docker/build-push-action@v4
      with:
        context: ./tools/container-build/base-devel
        file: ./tools/container-build/base-devel/Containerfile
        build-args: |
          ARCH=${{ matrix.platform }}
        platforms: ${{ steps.prepare_image.outputs.platform }}
        tags: 
        - archlinux-${{ matrix.platform }}:base-devel
        - ghcr.io/valorekhov/archlinux-${{ matrix.platform }}:base-devel
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        push: true

  build-makepkg-image:
    runs-on: ubuntu-latest
    name: Build gha-makepkg images
    if: github.event.inputs.arch == '' || github.event.inputs.arch == null || github.event.inputs.arch == matrix.platform
    strategy:
      matrix:
        platform: 
        - amd64
        - arm64v8
        - armv7hf
    steps:

    - name: Set up QEMU
      if: matrix.platform != 'amd64'
      uses: docker/setup-qemu-action@v2

    - name: Login to GitHub docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull down ${{ matrix.platform }} base-devel image
      id: pull_image
      run: |
        if [ '${{ matrix.platform }}' =  'amd64' ] ; then 
          docker pull archlinux:base-devel
          docker tag archlinux:base-devel archlinux-amd64:base-devel
        else
          docker pull ghcr.io/valorekhov/archlinux-${{ matrix.platform }}:base-devel
          docker tag ghcr.io/valorekhov/archlinux-${{ matrix.platform }}:base-devel archlinux-${{ matrix.platform }}:base-devel
        fi

        # Convert docker ARCH to archlinux-arm ARCH
        switch ('${{ matrix.platform }}') {
          'amd64' { $arch = 'x86_64' }
          'arm64v8' { $arch = 'aarch64' }
          'armv7hf' { $arch = 'armv7hf' }
        }
        echo "arch=$arch" >> $GITHUB_ENV

        switch ('${{ matrix.platform }}') {
          'amd64' { $platform = 'linux/amd64' }
          'arm64v8' { $platform = 'linux/arm64' }
          'armv7hf' { $platform = 'linux/arm/v7' }
        }
        echo "platform=$platform" >> $GITHUB_ENV

    - name: Build `gha-makepkg` image
      uses: docker/build-push-action@v4
      with:
        context: ./.github/actions/makepkg
        file: ./.github/actions/makepkg/Dockerfile
        build-args: |
          ARCH='-${{ matrix.platform }}'
        platforms: ${{ steps.pull_image.outputs.platform }}
        tags: 
        - ghcr.io/valorekhov/archlinux-${{ steps.pull_image.outputs.arch }}:latest
        - ghcr.io/valorekhov/archlinux-${{ matrix.platform }}:latest
        # cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true