name: Conditional Makefile rebuild

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in PKGBUILD folders
        id: check_PKGBUILDs
        run: |
          git diff --name-only HEAD^..HEAD -- 'PKGBUILDs/*/PKGBUILD' 'PKGBUILDs-extra/*/PKGBUILD' > /tmp/changed_PKGBUILDs.txt
          if grep -qE 'PKGBUILDs/|PKGBUILDs-extra/' /tmp/changed_PKGBUILDs.txt; then
            echo "PKGBUILDs changed. Updating .SCRINFO files..."
            while IFS= read -r file; do
              pkgbuild_dir="$(dirname "$file")"
              pusd "$pkgbuild_dir"
              makepkg --printsrcinfo > .SRCINFO 
              popd
            done < changed_files.txt
            echo "::set-output name=has_changes::true"
          fi

      - name: Check for changes in aur.lock
        id: check_aur_lock
        run: |
          if git diff --name-only HEAD^..HEAD -- aur.lock | grep -q 'aur.lock'; then
            echo "aur.lock changed."
            echo "::set-output name=has_changes::true"
          fi

      - name: Check for changes in PKGBUILDs and aur.lock
        if: steps.check_PKGBUILDs.outputs.has_changes == 'true' || steps.check_aur_lock.outputs.has_changes == 'true'
        run: |
          echo "Changes detected. Rebuilding Makefile..."
          run: ./generate-makefile.ps1
          shell: pwsh

      - name: Commit changes
        run: |
          git config --local user.email "ovos-arch-buildbot@noemail.local"
          git config --local user.name "OVOS Arch BuildBot"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update Makefile"
          git push
